# Generated by Django 4.2.2 on 2023-07-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoralTraits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=100)),
                ('toxicity_level', models.CharField(max_length=50)),
                ('rareity', models.CharField(max_length=50)),
                ('coral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='main_app.coral')),
            ],
            options={
                'ordering': ['diet'],
            },
        ),
    ]
